/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Metrics } from "./Metrics";
import { MetricsCountArgs } from "./MetricsCountArgs";
import { MetricsFindManyArgs } from "./MetricsFindManyArgs";
import { MetricsFindUniqueArgs } from "./MetricsFindUniqueArgs";
import { CreateMetricsArgs } from "./CreateMetricsArgs";
import { UpdateMetricsArgs } from "./UpdateMetricsArgs";
import { DeleteMetricsArgs } from "./DeleteMetricsArgs";
import { User } from "../../user/base/User";
import { MetricsService } from "../metrics.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Metrics)
export class MetricsResolverBase {
  constructor(
    protected readonly service: MetricsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Metrics",
    action: "read",
    possession: "any",
  })
  async _metricsItemsMeta(
    @graphql.Args() args: MetricsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Metrics])
  @nestAccessControl.UseRoles({
    resource: "Metrics",
    action: "read",
    possession: "any",
  })
  async metricsItems(
    @graphql.Args() args: MetricsFindManyArgs
  ): Promise<Metrics[]> {
    return this.service.metricsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Metrics, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Metrics",
    action: "read",
    possession: "own",
  })
  async metrics(
    @graphql.Args() args: MetricsFindUniqueArgs
  ): Promise<Metrics | null> {
    const result = await this.service.metrics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Metrics)
  @nestAccessControl.UseRoles({
    resource: "Metrics",
    action: "create",
    possession: "any",
  })
  async createMetrics(
    @graphql.Args() args: CreateMetricsArgs
  ): Promise<Metrics> {
    return await this.service.createMetrics({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Metrics)
  @nestAccessControl.UseRoles({
    resource: "Metrics",
    action: "update",
    possession: "any",
  })
  async updateMetrics(
    @graphql.Args() args: UpdateMetricsArgs
  ): Promise<Metrics | null> {
    try {
      return await this.service.updateMetrics({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Metrics)
  @nestAccessControl.UseRoles({
    resource: "Metrics",
    action: "delete",
    possession: "any",
  })
  async deleteMetrics(
    @graphql.Args() args: DeleteMetricsArgs
  ): Promise<Metrics | null> {
    try {
      return await this.service.deleteMetrics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Metrics): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
